- Home:
  - UniFi Network:
      - icon: unifi
        href: https://unifi/network/default/dashboard
  - Ubiquite Account:
      - icon: unifi
        href: https://account.ui.com/login?redirect=https%3A%2F%2Funifi.ui.com%2F
